run-name: release ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'dol_no_longer_decaying.mod.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        artifacts: "dol_no_longer_decaying.mod.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
