run-name: release ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - uses: edgarrc/action-7z@v1
      with:
       args: 7z a "-tzip" "-mm=Deflate" "-mx=9" dol_no_longer_decaying.mod.zip boot.json README.md
    - name: Upload Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        artifacts: "dol_no_longer_decaying.mod.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
